---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - openssh-server
    - openssh-client

- name: global config
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart ssh

- name: "add ssh {{ admin_user_group }} group"
  group:
    name: "{{ admin_user_group }}"
    state: present

- name: "add ssh {{ admin_user }} user"
  user:
    name: "{{ admin_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    comment: "Cluster admin"
    state: present
    group: "{{ admin_user_group }}"
    shell: /bin/zsh

- name: add public key to authorized keys
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_authorized_key }}"
    exclusive: yes

- name: "allow '{{ admin_user_group }}' group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ admin_user_group }}'
    line: '%{{ admin_user_group }} ALL=(ALL) NOPASSWD: ALL'
