galaxy_info:
  author: Jérémy Baumgarth
  description: Install and configure fail2ban, you can add your jails with yaml list variables
  company: Amiral Web
  license: MIT
  min_ansible_version: 2.1
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - wily
      - xenial
    - name: Debian
      versions:
      - jessie
  galaxy_tags:
    - fail2ban
    - security
    - iptables
    - fail2ban
