galaxy_info:
  author: Jérémy Baumgarth
  description: Install and configure Nginx, add your own virtualhosts from yaml variables
  company: Amiral Web
  license: MIT
  min_ansible_version: 2.1
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - wily
      - xenial
    - name: Debian
      versions:
      - jessie
  galaxy_tags:
    - Nginx
    - webserver
    - lemp
