galaxy_info:
  author: Jérémy Baumgarth
  description: Install and configure Oh My Zsh for your personal user
  company: Amiral Web
  license: MIT
  min_ansible_version: 2.1
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - wily
      - xenial
    - name: Debian
      versions:
      - jessie
  galaxy_tags:
    - shell
    - customization
    - ohmyzsh
dependencies: []
