---

- name: install
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - haproxy

- name: config
  template:
    src:  haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
  notify:
    - haproxy restart

- name: services start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - haproxy