---

- name: install apt package
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - supervisor

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisord

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/supervisor/{{ item }}"
  with_items:
    - supervisord.conf
  notify:
    - restart supervisor

- name: programs config
  template:
    src: "conf.d/{{ item }}.conf.j2"
    dest: "/etc/supervisor/conf.d/{{ item }}.conf"
  with_items: "{{ programs }}"
  notify:
    - restart supervisor
  when: programs is defined

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - supervisor