---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - curl
    - wget
    - htop
    - python-pip

- name: install pip packages
  pip:
    name: httpie