---

# Default apache configuration
apache_user: www-data
apache_user_group: www-data
apache_port: 80
apache_www_root: /srv/www
apache_macros:
  - common-nofpm
  - common
  - commonREST
  - php-fpm
  - ssl-with-chain
  - ssl
apache_modules:
  - proxy.load
  - proxy_fcgi.load
  - proxy_http.load
  - proxy_ftp.load
  - proxy_connect.load
  - macro.load
  - rewrite.load
  - headers.load

# Add virtualhosts to sites-available and sites-enabled directories
apache_vhosts:
  - default
  - custom_vhosts

# Add your own vhosts, simply override apache_custom_vhosts to fit your needs
apache_custom_vhosts:
  - { ServerName: test.local, DocumentRoot: /srv/www }

# Specific link with php fpm
php_fpm_socket_path: /var/run/php5-fpm.sock
