---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - memcached

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
  with_items:
    - memcached.conf
  notify:
    - restart memcached

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - memcached
