---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - apache2
    - apache2-utils

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apache2/{{ item }}"
    owner: root
    group: root
  with_items:
    - apache2.conf
  notify:
    - restart apache

- name: enable modules
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_modules }}"
  notify:
    - restart apache

- name: create macros folder
  file:
    path: /etc/apache2/macros
    state: directory
    owner: root
    group: root

- name: add macros
  template:
    src: "macros/{{ item }}.macro.j2"
    dest: "/etc/apache2/macros/{{ item }}.macro"
    owner: root
    group: root
  with_items:
    - "{{ apache_macros }}"
  notify:
    - restart apache

- name: remove default configuration
  file:
    dest: "/etc/apache2/{{ item }}"
    state: absent
  with_items:
    - sites-available/*
    - sites-enabled/*
  notify:
    - restart apache

- name: add vhosts
  template:
    src: "vhosts/{{ item }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    owner: root
    group: root
  with_items:
    - "{{ apache_vhosts }}"
  notify:
    - restart apache

- name: enable vhosts
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item }}.conf"
    state: link
  with_items:
    - "{{ apache_vhosts }}"
  notify:
    - restart apache

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - apache2
