---

- name: set php_executable
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: check current install
  stat: "path={{ composer_path }}"
  register: composer_bin

- name: download installer
  get_url:
    url: "{{ composer_download_url }}"
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: run installer
  command: >
    {{ php_executable }} composer-installer.php {% if composer_version != '' %} --version={{ composer_version }}{% endif %}
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: move into globally-accessible location
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}
  when: not composer_bin.stat.exists

- name: add global composer config
  template:
    src: config.json.j2
    dest: /root/.composer/config.json
