---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/mysql/{{ item }}"
    owner: root
    group: root
  with_items:
    - my.cnf
  notify:
    - restart mysql

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - mysql

- name: create mysql databases
  mysql_db:
    name:      "{{ default_database_name }}"
    encoding:  "{{ default_database_encoding|default('utf8') }}"
    collation: "{{ default_database_collation|default('utf8_general_ci') }}"
    state:     "{{ default_database_state|default(omit) }}"

- name: create mysql users
  mysql_user:
    name:     "{{ default_user_name }}"
    password: "{{ default_user_password|default(omit) }}"
    host:     "{{ default_user_host|default('localhost') }}"
    priv:     "{{ default_user_priv }}"
    state:    "{{ default_user_state|default(omit) }}"
