---

- src: jebovic.mailhog
  name: mailhog

- src: jebovic.fluentd
  name: fluentd

- src: jebovic.java
  name: java

- src: jebovic.elasticsearch
  name: elasticsearch

- src: jebovic.statsd
  name: statsd

- src: jebovic.supervisor
  name: supervisor
