---

- name: install packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - mongodb
    - python-pymongo

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - mongodb