galaxy_info:
  author: Jérémy Baumgarth
  description: Download, install and configure Mailhog, a great mail catcher
  company: Amiral Web
  license: MIT
  min_ansible_version: 2.1
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - wily
      - xenial
    - name: Debian
      versions:
      - jessie
  galaxy_tags:
    - mailhog
    - sendmail
    - mailcatcher
    - mail
