---

# Base playbook for every servers
- hosts: all
  become: true
  become_method: sudo
  roles:
    - { role: ssh }
    - { role: init }
    - { role: ufw }
    - { role: fail2ban }
    - { role: ohmyzsh }
    - { role: newrelic }
    - { role: sysdig }
    - { role: redis }
