---

# Include Base playbook for common tasks
- include: base.yml

# Specific playbook for go servers, including MongoDB for projects needs
- hosts: dockerservers
  become: true
  become_method: sudo
  roles:
    - { role: docker }
