---

# Include Base playbook for common tasks
- include: base.yml

# Specific playbook for monitoring servers
- hosts: monitoringservers
  become: true
  become_method: sudo
  roles:
    - { role: nodejs, tags: ['monitoring', 'nodejs'] }
    - { role: fluentd, tags: ['monitoring', 'fluentd'] }
    - { role: java, tags: ['monitoring', 'java'] }
    - { role: elasticsearch, tags: ['monitoring', 'elasticsearch'] }
    - { role: supervisor, tags: ['monitoring', 'supervisor'] }
#    - { role: _statsd, tags: ['monitoring', '_statsd'] }
#    - { role: _graphite, tags: ['monitoring', '_graphite'] }
#    - { role: _grafana, tags: ['monitoring', '_grafana'] }
