---

# Include Base playbook for common tasks
- include: base.yml

# Specific playbook for every webservers, including different projects needs
- hosts: webservers
  become: true
  become_method: sudo
  roles:
    - { role: haproxy, tags: ['web', 'haproxy'] }
    - { role: php, tags: ['web', 'php'] }
    - { role: memcache, tags: ['web', 'memcache'] }
    - { role: mysql, tags: ['web', 'mysql'] }
    - { role: mongodb, tags: ['web', 'mongodb'] }
    - { role: fluentd, tags: ['web', 'fluentd'] }
    - { role: supervisor, tags: ['web', 'supervisor'] }

# Specific lemp environment for webservers (Nginx)
- hosts: lempstack
  become: true
  become_method: sudo
  roles:
    - { role: nginx, tags: ['web', 'nginx'] }

# Specific lamp environment for webservers (Apache)
- hosts: lampstack
  become: true
  become_method: sudo
  roles:
    - { role: apache, tags: ['web', 'apache'] }
