---

# firewall rules
ufw_rules:
  - { port: 22, rule: allow }
  - { port: 80, rule: allow }
  - { port: 443, rule: allow }
  - { port: 8025, rule: allow }  # mailhog UI
  - { port: 9988, rule: allow }  # supervisor UI
  - { port: 9201, rule: allow }  # elasticsearch
  - { port: 9301, rule: allow }  # elasticsearch TCP transport
  - { port: 5601, rule: allow }  # kibana
  - { port: 24224, rule: allow } # fluentd forwarder
